In [118]:
import numpy as np

class Perceptron(object):
    """Impleents a perceptron network """
    
    def __init__(self,input_size,lr=1,epochs=10):
        self.W = np.zeros(input_size+1)
        # add one for bias
        self.epochs = epochs
        self.lr = lr
        
        
    
    def fit(self,X,d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y
                self.W = self.W + self.lr * e * np.insert(X[i],0,1)    
                
        
    def activation_fn(self,x):
        return 1 if x >= 0 else 0
    
    
    def predict(self,x):
        x = np.insert(x,0,1)
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a
    
    


In [119]:
X = np.array([
        [0,0],
        [0,1],
        [1,0],
        [1,1]
    ])

In [120]:
d = np.array([0,0,0,1])


In [121]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [122]:
d

array([0, 0, 0, 1])

In [123]:
perceptron = Perceptron(input_size=2)


In [124]:
perceptron.W

array([0., 0., 0.])

In [125]:
perceptron.fit(X,d)

In [126]:
perceptron.W

array([-3.,  2.,  1.])

In [127]:

print(perceptron.W)

[-3.  2.  1.]


In [129]:
perceptron.predict(np.asarray([0,0]))

0

In [130]:
mp = Perceptron(5)
x = np.asarray([1,1,0,0,0])
mp.predict(x)

1

In [131]:
mp.activation_fn(10)

1

In [132]:
mp.W

array([0., 0., 0., 0., 0., 0.])

 ## 1) 
 
 ### __init__ Fonksiyonu
 Ağırlık vektörünü oluşturmak için fonksiyon girdi alıyor. Sapmayı dahil edebilmek için bir arttırıyoruz. Fonksiyona devir sayısı ve öğrenme oranını dışarıdan eklenebilir. Parametre olarak eklendiği için değiştirilebilirler.
 
 
### fit Fonksiyonu
Tüm eğitim seti verilerini yineliyoruz. Ayrıca ağırlığı devir sayımız kadar değiştiriyoruz.
Ağırlık  güncellenirken  sapmayı girdiye ekliyoruz. Sonra tahmin oluşturarak hatamızı hesaplayabiliriz. Ayrıca güncelleme kuralına dikkat ederek yapıyoruz. Makine eğitme fonksiyonu olarak işlem yapar.

### activation_fn Fonksiyonu
Bu fonksiyon eşik değeri belirler.Eğer girdi 0 dan büyük veya eşitse 1 değilse 0 döndürüyoruz. Bu işlemi yaparak gelen input değeri için çıkacak output değerini buluruz.


### predict Fonksiyonu
Girdiyi çalıştırmak ve çıktı döndürmek için yazılan tahmin fonksiyonudur.Eğilimi giriş vektörüne ekliyoruz ardından iç çarpımı hesaplıyoruz. Aktivasyon fonksiyonunu kullanıyoruz. Makineyi eğittikten sonra input'un sonucunu tahmin ediyoruz.


## 2) 


###  XOR İşlemi Sonucu

X = np.array([
        [0,0],
        [0,1],
        [1,0],
        [1,1]
    ])

d = np.array([0,1,1,0])


perceptron = Perceptron(input_size=2)

perceptron.fit(X,d)

print(perceptron.W) ->> [ 0. -1.  0.]

### Fonksiyon sonucu hesaplanan değerler

perceptron.predict(np.asarray([0,0])) --> 1

perceptron.predict(np.asarray([1,0])) --> 0

perceptron.predict(np.asarray([0,1])) --> 1

perceptron.predict(np.asarray([1,1])) --> 0

Yapılan işlemlerden sonra çıkan sonuçta XOR işlemi yapıldığında sonuçlarımız doğru outpuları vermedi.
Yalnızca doğrusal ayrılabilen sorunları çözebilmektedirler. XOR ise doğrusal olarak ayrılamadığından tek katmanlı işlemler için XOR kapısı için kullanmamalıyız.

## 3)

 X inputları, d ise beklenen outputları ifade etmekter. Öğrenci sayımız 40 olduğu için öğrenci imzaları için 40 elemanlı bir dizi gereklidir. Predict fonksiyonuna öğrenci imzaları verilir. Girdiler işlenir ve sonucunda imzanın kime ait olduğu hakkında bilgi output olarak elde edilmiş olur.

## 4)

Yapılan denemeler sonucu elde edilen toplam verilere hatalı verilerinin toplamını bölerek hatalı olma olasığını buluruz.Böyle hata oranını hesaplamış oluruz.
